"""DAL: device profile, decision state/universal/provider, executions

Revision ID: 4d888da5dbe2
Revises: 66179394b492
Create Date: 2026-06-10 15:39:21.818809
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4d888da5dbe2'
down_revision: str | None = '66179394b492'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_executions',
    sa.Column('robot_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=True),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='executionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_executions_action_id'), 'action_executions', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_executions_decision_id'), 'action_executions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_action_executions_robot_id'), 'action_executions', ['robot_id'], unique=False)
    # Server defaults make these safe to add to tables that already hold rows.
    op.add_column('decisions', sa.Column('universal_actions', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('decisions', sa.Column('state', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('decisions', sa.Column('provider', sa.String(length=64), nullable=True))
    op.add_column('robots', sa.Column('firmware_version', sa.String(length=64), nullable=True))
    op.add_column('robots', sa.Column('protocol_version', sa.String(length=32), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'protocol_version')
    op.drop_column('robots', 'firmware_version')
    op.drop_column('decisions', 'provider')
    op.drop_column('decisions', 'state')
    op.drop_column('decisions', 'universal_actions')
    op.drop_index(op.f('ix_action_executions_robot_id'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_decision_id'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_action_id'), table_name='action_executions')
    op.drop_table('action_executions')
    # ### end Alembic commands ###
