"""task engine: priority and source

Revision ID: 7769bd8f9aa4
Revises: a496f75cae9e
Create Date: 2026-06-08 11:07:01.308317
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '7769bd8f9aa4'
down_revision: str | None = 'a496f75cae9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('source', sa.Enum('assigned', 'robot', name='tasksource', native_enum=False, length=16), nullable=False))
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_column('tasks', 'source')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
