"""add robots.paused

Revision ID: 90c4530475f8
Revises: 4d888da5dbe2
Create Date: 2026-06-11 23:47:46.372286
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '90c4530475f8'
down_revision: str | None = '4d888da5dbe2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('paused', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'paused')
    # ### end Alembic commands ###
