"""add robots.last_seen_at

Revision ID: a496f75cae9e
Revises: ead7fce06ab1
Create Date: 2026-06-07 16:42:28.960524
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a496f75cae9e'
down_revision: str | None = 'ead7fce06ab1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'last_seen_at')
    # ### end Alembic commands ###
