"""initial schema

Revision ID: ead7fce06ab1
Revises: 
Create Date: 2026-06-07 16:00:01.956087
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ead7fce06ab1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('robot_type', sa.String(length=128), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'error', name='robotstatus', native_enum=False, length=16), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_robot_type'), 'robots', ['robot_type'], unique=False)
    op.create_index(op.f('ix_robots_status'), 'robots', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('robot_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='taskstatus', native_enum=False, length=16), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_robot_id'), 'tasks', ['robot_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('telemetry',
    sa.Column('robot_id', sa.String(length=32), nullable=False),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_robot_id'), 'telemetry', ['robot_id'], unique=False)
    op.create_table('decisions',
    sa.Column('robot_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('frame_url', sa.String(length=1024), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_robot_id'), 'decisions', ['robot_id'], unique=False)
    op.create_index(op.f('ix_decisions_task_id'), 'decisions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_task_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_robot_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_telemetry_robot_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_robot_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_robots_status'), table_name='robots')
    op.drop_index(op.f('ix_robots_robot_type'), table_name='robots')
    op.drop_table('robots')
    # ### end Alembic commands ###
